import Head from "next/head";
import Link from "next/link";
import { Grid, Container, Card, Text } from "@nextui-org/react";

export default function Categorias() {
  return (
    <div>
      <Head>
        <title>Categorias</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create-next-app" />
      </Head>
      <div>
        <Container>
          <Grid.Container gap={2} justify="center">
            <Grid sm={12} md={5}>
              <Card css={{ mw: "330px" }}>
                <Text h4>Proximamente</Text>
                <Text>🚀 Vas a poder ver por plataforma los juegos gratis</Text>
                <Card.Footer>Visit source code on GitHub.</Card.Footer>
              </Card>
            </Grid>
          </Grid.Container>
        </Container>
      </div>
    </div>
  );
}
